# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bouguern Abderrahmane
title: M2 Cybersecurity
email: bougabderrahmane@gmail.com
website: abderrahmane1010.github.io/notes_/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  abderrahmane1010
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: abd3rr4hm4n3
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Abderrahmane and I'm an embedded systems and connected objects engineer with a Master's degree in cybersecurity.

  I am most skilled in: <mark>Developing tools for security</mark>, <mark>Web pentesting</mark>, <mark>Compilers</mark> and <mark>Pentesting</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Verimag Laboratory 
        link: https://www-verimag.imag.fr/
        # link_text: boringcompany.com
        sub_title: Software Security Code Analyst Engineer
        caption: Sep 2022 - Feb 2024
        quote: >
          Analyzing code for security is like peering into the DNA of a digital organism to safeguard its health in the cyber ecosystem.
        description: | # this will include new lines to allow paragraphs
            Specialized in analyzing software code for security vulnerabilities.
            Conducted in-depth assessments of code to identify and mitigate potential security risks.
            Focused on the analysis of software protections against physical attacks, including fault injection and auxiliary channel attacks.
            Utilized LLVM (Low Level Virtual Machine) for comprehensive analysis at the code level.
            Developed solutions in C++ using the LLVM API, implementing countermeasure passes for enhanced security.
            Applied symbolic execution (KLEE Symbolic Execution Engine) for thorough path exploration and vulnerability detection.
      - layout: left
        title: The Verimag Laboratory 
        link: https://www-verimag.imag.fr/
        # link_text: boringcompany.com
        sub_title: PFE Software-Based Fault Injection Countermeasures Analysis
        caption: Jan 2022 - Sep 2022
        quote: >
          Research: where the curious go to play, the dedicated go to work, and the persistent go to discover
        description: | # this will include new lines to allow paragraphs
            Conducted analysis of software protections against physical attacks, specifically focusing on fault injection and auxiliary channel attacks.
            Applied attack techniques, including fault injections and auxiliary channel attacks.
            Performed analysis at the LLVM (Low Level Virtual Machine) level.
            Developed solutions in C++ using the LLVM API.
            Implemented countermeasure passes for protection against fault injections.
            Analyzed C-level code for vulnerability assessment.
            Utilized symbolic execution (KLEE Symbolic Execution Engine) for path exploration.
      - layout: left
        title: ARYLINK
        link: https://arlynk.com/
        # link_text: boringcompany.com
        sub_title: Full-Stack Developer - MERN Stack
        caption: Jun 2021 - Sep 2021
        quote: >
          MERN stack: Uniting the web's building blocks for powerful full stack development
        description: | # this will include new lines to allow paragraphs
          Utilized the MERN (MongoDB, Express.js, React, Node.js) stack to develop the "Help Center" platform.
      - layout: left
        title: Opinaka
        link: https://home.opinaka.com/home/
        # link_text: boringcompany.com
        sub_title: Front-End Development
        caption: Jun 2020 - Aug 2022
        quote: >
          React: Empowering developers to build dynamic and delightful user interfaces with ease.
        description: | # this will include new lines to allow paragraphs
          Conducted in-depth study on JavaScript frameworks, with a focus on React, for the implementation of visualization models. Executed integration and visualization of JavaScript scripts utilizing Kibana and Elasticsearch.
  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Front-End Development for a Java-Like Object-Oriented Language Compiler
        link: github.com/abderrahmane1010/SecureWebAudit
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Compilers: the only thing that can find 99 problems in 5 seconds.
        description: | # this will include new lines to allow paragraphs
          This project involves designing and implementing the front-end of a compiler for an object-oriented programming language that closely resembles Java. Built using Java, the front-end processes source code by performing lexical analysis, syntax analysis, and semantic checks. 
      - layout: top-middle
        title: SecureWebAudit
        link: github.com/abderrahmane1010/SecureWebAudit
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Secure your web app before hackers turn it into their playground.
        description: | # this will include new lines to allow paragraphs
          SecureWebAudit is a web security analysis tool designed to audit HTTP headers and detect XSS (Cross-Site Scripting) vulnerabilities in websites. It aims to provide insights into the security configurations of web headers and identify potential areas where a website may be susceptible to XSS attacks. 
      - layout: top-middle
        title: ARPRecon
        link: github.com/abderrahmane1010/ARPRecon
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ARP: The networking world's version of 'Who's Who.'
        description: | # this will include new lines to allow paragraphs
          ARPRecon is a sophisticated, highly specialized tool designed for monitoring and securing networks against ARP-related vulnerabilities and threats. This tool stands out as a comprehensive solution for network administrators, cybersecurity experts, and anyone concerned with network integrity and security. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Grenoble INP - Ensimag
        caption: 2021 - 2022
        sub_title: M2 Cybersecurity
        quote: >
          National School of Computer Science and Applied Mathematics of Grenoble
        description: | # this will include new lines to allow paragraphs
          Top French educational institution in Informatics, Applied Mathematics and Telecommunications, pioneer in the field of information processing, Ensimag evolves to remain the reference in this field. 
      - layout: left
        title: Grenoble INP - PHELMA
        caption: 2019 - 2022
        sub_title: Embedded systems & Connected objects
        quote: >
          School of Engineering in Physics, Electronics and Materials Science - Grenoble INP - Phelma
        description: | # this will include new lines to allow paragraphs
          Grenoble INP – Phelma is the school for scientific diversity. It offers its students courses in various fields with a promising future: micro and nano-technologies (micro / nano-electronics, nano-sciences, materials, health, building, etc.), energy...
      - layout: left
        title: Preparatory classes - TSI 
        caption: 2020 - 2020
        sub_title: M2 Cybersecurity
        quote: >
          TSI (Technologie et Sciences de l'Ingénieur) preparatory class.
        description: | # this will include new lines to allow paragraphs
          Two years in preparatory classes in Mathematics and IEE (Information processing, electrical engineering 
          and electronics)."Classes préparatoires" are two-year intensive preparatory courses in France, aimed at high-achieving students who wish to enter the prestigious grandes écoles—elite higher education institutions. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gymnastics
      - Aviron

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
